version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
    nextjs:
        ports:
        - 3000:3000
        build:
            context: ./nextjs
            dockerfile: Dockerfile
        volumes:
            - ./nextjs:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next